env:
    BUILD_USER: ryujinXprjkt
    BUILD_BUILD_HOST: Ubuntu
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    TG_TOKEN: "5398876930:AAHH5brJSf5NG5lzlvh-OaaUulc1GstcJNg"
    TG_CHAT_ID: "ENCRYPTED[1c07c1fd35bac920ac606680e4bd133632f737b4b4df32476ec26c2ebd3dd367391bdca4395411b41d576bb0f6d6477b]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: ryujinxd/ubuntu:latest
      cpu: 8
      memory: 32G

  Environment_script:
      - cat /etc/os*
      - env
      - git config --global user.email "sahruldarmian212@gmail.com" -y && git config --global user.name "tzuyu-xd" -y

  Sync_script:
      - ./download.sh

  Compile_script:
      - ./compile.sh 
